export const MinorQuirks = ['Will not ever drink alcohol',
'Must touch their weapon every minute',
'Doesn\'t trust any animals ever',
'Religiously copies other people\'s cultures always',
'Afraid of small animals when they see them',
'Needs skip the sleep cycle once a week',
'Never eat anything with a face',
'Always takes trophies from their kills',
'Always wears excessive amounts of jewelry and trinkets',
'Always wears only one color',
'Writes journal detailing all events daily',
'Is always incredibly awkward around aliens, other age groups, other genders',
'Must have total darkness when sleeping',
'Must have some light when sleep',
'Always cries when hearing music or seeing art',
'Refuses to ever handle money',
'Meticulously collects one type of item, adds one daily',
'Must draw strange symbols outdoors daily',
'Talks to inanimate objects daily, hears them talk back',
'Always answers questions with questions',
'Invents their own langauge, once per day speak it to people',
'Daily breaks out in song and dance during converation',
'Always gives unsolicited advice to strangers',
'Uses unnecessary methaphors in every conversation',
'Don\'t trust people who don\'t remember their name',
'Always makes up nicknames for people',
'Must apologise- in person, to anyone they hurt every time they hurt someone',
'Must always speak the slowest during conversation',
'Must not ever lie or mislead when speaking',
'Must always refer to themselves in third person',
'Must daily speak with fake accent',
'Must not ever engage in small talk'];