import React from "react";
import StarSystem, { PlanetRings } from "../Lore/StarSystem";

const Tonati = () => <StarSystem
    name='Star System Tonati'
    description='One of many fringe worlds, Tonati considerably advanced with two habitable planets'
    roguePlanetoids={[]}
    stars={[{
        name: 'Tonati',
        description: 'Intense radiation makes the innermost part of the system mostly inaccessible. With a staggering luminosity of 15 times that of the Sun also means that the zone of habitabilty is much larger and farther out.',
        classification: 'A',
        mass: 2.7,
        age: 4.1,
        axialTilt: 0,
        dayPeriod: 3600 * 24,
        imageURL: 'images/texture_star_tonati.png',
        bodyType: 'star',
        planetoids: [{
            name: 'Chantico',
            description: 'Chantico rotates extremely quickly, a day lasting only 160 minutes. This planet is a smoldering radioactive hellscape under the Tonati sun, rivers of magma flow across the surface that is never able to cool down',
            mass: 0.09,
            age: 3.8,
            classification: 'rocky metallic',
            satelites: [],
            atmosphere: "none",
            atmosphericPressure: 0,
            hydrosphere: "none",
            surfaceGravity: 0.5,
            temperatureRange: [1000, 1200, 1300],
            orbitDistance: { apoapsis: .2, periapsis: .2, unit: 'AU' },
            feature: 'extreme radiation',
            imageURL: 'images/texture_planet_molten.jpg',
            axialTilt: 6,
            dayPeriod: 3600 * 24 * 10,
            bodyType: 'planetoid',
        },
        {
            name: 'Teylaloc',
            description: 'Large rocky planet with a powerful magnetic field to protect it from the intense solar radiation. Constant thunderstorms and rains of molten lead and graphite makes this planets surface inaccessible.',
            mass: 1.8,
            age: 3.9,
            classification: 'rocky',
            satelites: [],
            atmosphere: "thick carbon dioxide",
            atmosphericPressure: 1700,
            hydrosphere: "none",
            surfaceGravity: 1.5,
            temperatureRange: [320, 340, 360],
            orbitDistance: { apoapsis: .7, periapsis: .7, unit: 'AU' },
            feature: 'constant planetwide thunderstorms',
            imageURL: 'images/texture_planet_pinkteal.jpg',
            axialTilt: 9,
            dayPeriod: 3600 * 11,
            bodyType: 'planetoid',
        },
        {
            name: 'Atlahua',
            description: 'Small rocky planet with a thin atmosphere of carbondioxide and radiogenic neon (formed by the radiation hitting the magnesium rich surface). Additionally two rings orbit this planet, the inner ring is mostly made of iron and the outer made of silicates. Indicating that they were formed from a failed planet.',
            mass: 0.7,
            age: 3.8,
            classification: 'rocky',
            satelites: [
                new PlanetRings({ apoapsis: 600, periapsis: 600, unit: 'km' }, [-90, 180, 250], 3.6, 0.01)
            ],
            atmosphere: "80% carbon dioxide, 19% neon, 1% argon",
            atmosphericPressure: 20,
            hydrosphere: "none",
            surfaceGravity: 1.5,
            temperatureRange: [190, 250, 370],
            orbitDistance: { apoapsis: 1.5, periapsis: 1.5, unit: 'AU' },
            imageURL: 'images/texture_planet_rocky.jpg',
            axialTilt: 1,
            dayPeriod: 3600 * 18,
            bodyType: 'planetoid',
        },
        {
            name: 'Ehecatl',
            description: 'Orange moss like flora covers the surface of this world, though the planet has no oceans or large bodies of surface water underground streams can be found. The atmosphere is composed of nitrogen and enough oxygen to breathe, however trace amounts of sulfides in the lower atmosphere makes long term exposure risky.  A small number of settlements exist on this planet, most of them depend on resources from space.',
            mass: 0.5,
            age: 3.7,
            classification: 'rocky',
            satelites: [],
            atmosphere: "60% nitrogen 38% oxygen, 1% argon, 1% ozone, trace sulfides",
            atmosphericPressure: 90,
            hydrosphere: "salt water",
            surfaceGravity: 0.65,
            temperatureRange: [20, 0, 70],
            orbitDistance: { apoapsis: 3.5, periapsis: 3.5, unit: 'AU' },
            feature: 'settlements',
            imageURL: 'images/texture_planet_orangegreen.jpg',
            axialTilt: -21,
            dayPeriod: 3600 * 27,
            bodyType: 'planetoid',
        },
        {
            name: 'Meztil',
            description: 'WIP',
            mass: 0.9,
            age: 3.7,
            classification: 'rocky',
            satelites: [],
            atmosphere: "70% nitrogen 29% oxygen, 1% argon",
            atmosphericPressure: 81,
            hydrosphere: "salt water",
            surfaceGravity: 0.9,
            temperatureRange: [-30, 0, 40],
            orbitDistance: { apoapsis: 4.2, periapsis: 4.2, unit: 'AU' },
            feature: 'settlements',
            imageURL: 'images/texture_planet_lush.jpg',
            axialTilt: 17,
            dayPeriod: 3600 * 28,
            bodyType: 'planetoid',
        },
        {
            name: 'Toci',
            description: 'WIP',
            mass: 65,
            age: 3.9,
            classification: 'gas giant',
            atmosphericPressure: 125320,
            satelites: [],
            atmosphere: "hydrogen helium",
            hydrosphere: "liquid hydrogen",
            surfaceGravity: 4,
            temperatureRange: [-130, 0, 80],
            orbitDistance: { apoapsis: 30, periapsis: 30, unit: 'AU' },
            imageURL: 'images/texture_planet_lime.jpg',
            axialTilt: 65,
            dayPeriod: 3600 * 4,
            bodyType: 'planetoid',
        },
        {
            name: 'Xolotl',
            description: 'WIP',
            mass: 1.2,
            age: 6.1,
            classification: 'rocky',
            satelites: [],
            atmosphere: "hydrogen",
            atmosphericPressure: 4,
            hydrosphere: "liquid methane",
            surfaceGravity: 4,
            temperatureRange: [-190, -180, -170],
            orbitDistance: { apoapsis: 79, periapsis: 79, unit: 'AU' },
            imageURL: 'images/texture_planet_cold.jpg',
            axialTilt: -90,
            dayPeriod: 3600 * 240,
            bodyType: 'planetoid',
        }
        ]

    }]}
/>;

export default Tonati;