import { Electricity, Vehicle } from "./Vehicles";

const WaterVehicles: Vehicle[] = [
    {
        name: 'paddle boat',
        medium: ['water'],
        passengers: 2,
        cargoKg: 400,
        fuelType: [],
        range: 0,
        topSpeed: 2,
        acceleration: 1,
        cost: 2000,
        description: 'basic paddleboat',
        parts: [],
    },
    {
        name: 'jetski',
        medium: ['water'],
        passengers: 4,
        cargoKg: 600,
        fuelType: [Electricity],
        range: 60,
        topSpeed: 55,
        acceleration: 7,
        cost: 10000,
        description: 'fast moving water ski',
        parts: [],
    },
    {
        name: 'speed boat',
        medium: ['water'],
        passengers: 8,
        cargoKg: 2000,
        fuelType: [Electricity],
        range: 100,
        topSpeed: 45,
        acceleration: 5,
        cost: 40000,
        description: 'electric speed boat',
        parts: [],
    },
    {
        name: 'yacht',
        medium: ['water'],
        passengers: 10,
        cargoKg: 60000,
        fuelType: [Electricity],
        range: 1000,
        topSpeed: 40,
        acceleration: 3,
        cost: 400000,
        description: 'luxury boat often fitted with solar panels to allow slow recharge anywhere. Has living quarters for all passengers.',
        parts: [],
    },
    {
        name: 'small ferry',
        medium: ['water'],
        passengers: 100,
        cargoKg: 80000,
        fuelType: [Electricity],
        range: 200,
        topSpeed: 30,
        acceleration: 3,
        cost: 300000,
        description: 'a simple ferry designed to carry many people or a batch of cargo a small distance. Has seats for all passengers or it can provide bunk beds for half (uses 90% of cargo mass)',
        parts: []
    },
    {
        name: 'large ferry',
        medium: ['water'],
        passengers: 1000,
        cargoKg: 800000,
        fuelType: [Electricity],
        range: 500,
        topSpeed: 30,
        acceleration: 3,
        cost: 800000,
        description: 'a simple ferry designed to carry many people or a batch of cargo a medium distance. Has seats for all passengers or it can provide bunk beds for half (uses 90% of cargo mass)',
        parts: []
    },
    {
        name: 'small freighter',
        medium: ['water'],
        passengers: 10,
        cargoKg: 2000000,
        fuelType: [Electricity],
        range: 1200000,
        topSpeed: 40,
        acceleration: 3,
        cost: 1000000,
        description: 'very small cargo ship outfitted with a micro fusion power',
        parts: [],
    },
    {
        name: 'freighter',
        medium: ['water'],
        passengers: 15,
        cargoKg: 10000000,
        fuelType: [Electricity],
        range: 1200000,
        topSpeed: 40,
        acceleration: 3,
        cost: 4000000,
        description: 'cargo ship equipped with micro fusion reactor for near unlimited range',
        parts: [],
    },
    {
        name: 'large freighter',
        medium: ['water'],
        passengers: 25,
        cargoKg: 50000000,
        fuelType: [Electricity],
        range: 1200000,
        topSpeed: 40,
        acceleration: 3,
        cost: 10000000,
        description: 'large cargo ship equipped with micro fusion reactor for near unlimited range',
        parts: [],
    },
    {
        name: 'cruiser',
        medium: ['water'],
        passengers: 1200,
        cargoKg: 2000000,
        fuelType: [Electricity],
        range: 2000000,
        topSpeed: 14,
        acceleration: 1,
        cost: 3500000,
        description: 'cruiser fitted with on board small fusion generator capable of running for years without refueling, weapon capable',
        parts: [],
    },
    {
        name: 'battleship',
        medium: ['water'],
        passengers: 1000,
        cargoKg: 20000000,
        fuelType: [Electricity],
        range: 2000000,
        topSpeed: 22,
        acceleration: 0.8,
        cost: 150000000,
        description: 'battleship fitted with on board small fusion generator, large railguns, laser cannons and missiles',
        parts: [],
    },
    {
        name: 'submarine',
        medium: ['water', 'subwater'],
        passengers: 40,
        cargoKg: 10000,
        fuelType: [Electricity],
        range: 1000000,
        topSpeed: 12,
        acceleration: 1,
        cost: 70000000,
        description: 'fusion powered submarine',
        parts: [],
    },
    {
        name: 'civilian submarine',
        medium: ['water', 'subwater'],
        passengers: 10,
        cargoKg: 10000,
        fuelType: [Electricity],
        range: 10000,
        topSpeed: 4,
        acceleration: 1,
        cost: 700000,
        description: 'battery powered submarine',
        parts: [],
    }
];

export default WaterVehicles;