import { Electricity, Vehicle } from "./Vehicles";

const WaterVehicles: Vehicle[] = [
    {
        name: 'paddle boat',
        medium: ['water'],
        passengers: 6,
        cargoKg: 50,
        fuelType: [],
        range: 0,
        topSpeed: 2,
        acceleration: 1,
        cost: 2000,
        description: 'basic paddleboat',
        parts: [],
    },
    {
        name: 'jetski',
        medium: ['water'],
        passengers: 2,
        cargoKg: 20,
        fuelType: [Electricity],
        range: 80,
        topSpeed: 55,
        acceleration: 7,
        cost: 10000,
        description: 'fast moving water ski',
        parts: [],
    },
    {
        name: 'speed boat',
        medium: ['water'],
        passengers: 8,
        cargoKg: 100,
        fuelType: [Electricity],
        range: 500,
        topSpeed: 45,
        acceleration: 5,
        cost: 40000,
        description: 'electric speed boat',
        parts: [],
    },
    {
        name: 'yacht',
        medium: ['water'],
        passengers: 20,
        cargoKg: 10000,
        fuelType: [Electricity],
        range: 12000,
        topSpeed: 40,
        acceleration: 3,
        cost: 100000,
        description: 'luxury boat often fitted with solar panels to allow slow recharge anywhere',
        parts: [],
    },
    {
        name: 'cruiser',
        medium: ['water'],
        passengers: 1200,
        cargoKg: 20000000,
        fuelType: [Electricity],
        range: 2000000,
        topSpeed: 14,
        acceleration: 1,
        cost: 3500000,
        description: 'cruiser fitted with on board small fusion generator capable of running for years without refueling',
        parts: [],
    },
    {
        name: 'battleship',
        medium: ['water'],
        passengers: 1000,
        cargoKg: 20000000,
        fuelType: [Electricity],
        range: 2000000,
        topSpeed: 22,
        acceleration: 0.8,
        cost: 150000000,
        description: 'battleship fitted with on board small fusion generator, large railguns and laser cannons',
        parts: [],
    },
    {
        name: 'submarine',
        medium: ['water', 'subwater'],
        passengers: 40,
        cargoKg: 10000,
        fuelType: [Electricity],
        range: 1000000,
        topSpeed: 12,
        acceleration: 1,
        cost: 70000000,
        description: 'fusion powered submarine',
        parts: [],
    }
];

export default WaterVehicles;