export const Weaknesses = [
    'Clumsy', 'Arrogant', 'Impatient', 'Lazy', 'Fearful', 'Stubborn', 'Short sighted', 'Selfish', 'Greedy', 'Narcissist', 'Aggressive', 'Passive', 'Trouble with teamwork',
    'Needs to be right', 'Cant handle criticism', 'Easily bored', 'Cynical', 'Close-minded', 'Shallow', ' Dishonesty', 'Unfair', 'Paranoid'
];

export const Needs = [
    'More money', 'More respect', 'Gain freedom', 'Destroy enemies', 'Make peace with enemies', 'Let go of negative feelings', 'make friends', 'grow up and take responsibility'
];

export const Desires = [
    'To be accepted/approved of by others', 'To know more and satisfy their curiosity', 'To consume', 'To have a family and protect and love them',
    'To act in honorable ways, to be honorable', 'To promote altruism or justice', 'To be become more independent', 'To create and enforce order',
    'To do physical activity', 'To gain power', 'To have romance', 'To accumulate wealth', 'To have friends', 'To be respected and have social status',
    'To find peace and tranquility', 'To get vengence on those that have wronged them',
];

export const Enemies = [
    'Another NPC', 'One of the players', 'An organization they compete with', 'The organization they work with'
];

export const Rumors = [

];

export const Secrets = [
    'Tells lies to people and asks them to keep it a secret', 'Has romantic or sexual thoughts about someone theyre not supposed to',
    'Has a secret work related ambition', 'Has a secret project theyre working on', 'Is secretly a criminal', 'Has a dark family secret',
    'Is a member of a secret society', 'Is a member of a secret cult or religion', 'Is spying on their workplace or society', 'Is leading a double life',
    'Has hidden away a stash of money', 'Has hidden away a huge stash of money', 'Has a secret debt to someone', 'Is in debt to a criminal organization',
    'Collects illegal items', 'Collects stolen items'
];

export const RedeemingQualities = [
    'Sincere',
    'Honest',
    'Understanding',
    'Loyal',
    'Truthful',
    'Trustworthy',
    'Intelligent',
    'Dependable',
    'Open-Minded',
    'Thoughtful',
    'Wise',
    'Considerate',
    'Good-Natured',
    'Reliable',
    'Mature',
    'Warm',
    'Earnest',
    'Kind',
    'Friendly',
    'Kind-Hearted',
    'Happy',
    'Clean',
    'Interesting',
    'Unselfish',
    'Good-Humored',
    'Honorable',
    'Humorous',
    'Responsible',
    'Cheerful',
    'Trustful',
    'Warm-Hearted',
    'Broad-Minded',
    'Gentle',
    'Well-Spoken',
    'Educated',
    'Reasonable',
    'Companionable',
    'Likable',
    'Trusting',
    'Clever',
    'Pleasant',
    'Courteous',
    'Quick-Witted',
    'Tactful',
    'Helpful',
    'Appreciative',
    'Imaginative',
    'Outstanding',
    'Self-Disciplined',
    'Brilliant',
    'Enthusiastic',
    'Level-Headed',
    'Polite',
    'Original',
    'Smart',
    'Forgiving',
    'Sharp-Witted',
    'Well-Read',
    'Ambitious',
    'Bright',
    'Respectful',
    'Efficient',
    'Good-Tempered',
    'Grateful',
    'Conscientious',
    'Resourceful',
    'Alert',
    'Good',
    'Witty',
    'Clear-Headed',
    'Kindly',
    'Admirable',
    'Patient',
    'Talented',
    'Perceptive',
    'Spirited',
    'Sportsmanlike',
    'Well-Mannered',
    'Cooperative',
    'Ethical',
    'Intellectual',
    'Versatile',
    'Capable',
    'Courageous',
    'Constructive',
    'Productive',
    'Progressive',
    'Individualistic',
    'Observant',
    'Ingenious',
    'Lively',
    'Neat',
    'Punctual',
    'Logical',
    'Prompt',
    'Accurate',
    'Sensible',
    'Creative',
    'Self-Reliant',
    'Tolerant',
    'Amusing',
    'Clean-Cut',
    'Generous',
    'Sympathetic',
    'Energetic',
    'High-Spirited',
    'Self-Controlled',
    'Tender',
    'Active',
    'Independent',
    'Respectable',
    'Inventive',
    'Wholesome',
    'Congenial',
    'Cordial',
    'Experienced',
    'Attentive',
    'Cultured',
    'Frank',
    'Purposeful',
    'Decent',
    'Diligent',
    'Realist',
    'Eager',
    'Poised',
    'Competent',
    'Realistic',
    'Amiable',
    'Optimistic',
    'Vigorous',
    'Entertaining',
    'Adventurous',
    'Vivacious',
    'Composed',
    'Relaxed',
    'Romantic',
    'Proficient',
    'Rational',
    'Skillful',
    'Enterprising',
    'Gracious',
    'Able',
    'Nice',
    'Agreeable',
    'Skilled',
    'Curious',
    'Modern',
    'Charming',
    'Sociable',
    'Modest',
    'Decisive',
    'Humble',
    'Tidy',
    'Popular',
    'Upright',
    'Literary',
    'Practical',
    'Light-Hearted',
    'Well-Bred',
    'Refined',
    'Self-Confident',
    'Cool-Headed',
    'Studious',
    'Adventuresome',
    'Discreet',
    'Informal',
    'Thorough',
    'Exuberant',
    'Inquisitive',
    'Easygoing',
    'Outgoing',
    'Self-Sufficient',
    'Casual',
    'Consistent',
    'Moral',
    'Self-Assured',
    'Untiring',
    'Hopeful',
    'Calm',
    'Strong-Minded',
    'Positive',
    'Confident',
    'Artistic',
    'Precise',
    'Scientific',
    'Orderly',
    'Social',
    'Direct',
    'Careful',
    'Candid',
    'Comical',
    'Obliging',
    'Self-Critical',
    'Fashionable',
    'Religious',
    'Soft-Hearted',
    'Dignified',
    'Philosophical',
    'Idealistic',
    'Soft-Spoken',
];