export const quirks = [
    'Always bored',
    'Angry drunk',
    'Annoyingly Cryptic',
    'Avant-garde',
    'Bigoted',
    'Bloody-Minded',
    'Boastful',
    'Bookworm',
    'Bossy',
    'Bully',
    'Calculating',
    'Can-do attitude',
    'Chatterbox',
    'Chirpy',
    'Collects small animals',
    'Compulsive Liar',
    'Condescending',
    'Conniving',
    'Conspiracy theorist',
    'Creep',
    'Decadent',
    'Ditz',
    'Egomaniac',
    'Exquisite dresser',
    'Extravagant',
    'Fanatically loyal',
    'Fast-talker',
    'Femme Fatale',
    'Fiercely ambitious',
    'Fits of melancholy',
    'Flamboyant',
    'Folksy Wisdom',
    'Gossip',
    'Hard-boiled',
    'Hears voices',
    'Hillbilly',
    'Hothead',
    'Hypochondriac',
    'Iconoclast',
    'Idealistic',
    'Illiterate',
    'Incredibly persistent',
    'Insightful observer',
    'Into crystals',
    'Jack of all Trades',
    'Jerk',
    'Klutz',
    'Knows everybody',
    'Life of the party',
    'Love-struck',
    'Mad genius',
    'Magnetic Personality',
    'Manic',
    'Master Orator',
    'Militantly Vegan',
    'Misanthrope',
    'Miser',
    'Mopey',
    'Naïve',
    'Nerd',
    'No-nonsense',
    'Obsessive',
    'Old Fart',
    'Overeducated',
    'Paranoid',
    'Perfect Manners',
    'Pouty',
    'Power-hungry',
    'Prickly',
    'Proselytizer',
    'Ruthless',
    'Sadist',
    'Self-destructive',
    'Self-important',
    'Self-pitying',
    'Senile',
    'Serene',
    'Shameless Flirt',
    'Slacker',
    'Slimy',
    'Slovenly',
    'Snarky',
    'Snitch',
    'Snob',
    'Social butterfly',
    'Sophist',
    'Spacey',
    'Terrible memory',
    'Thick',
    'Toady',
    'Totally unreliable',
    'Twitchy',
    'Vain',
    'Vengeful',
    'Village idiot',
    'Well-Travelled',
    'Whiner',
    'Wild Child',
    'Wisecracking',
    'World-weary'
];