import React from 'react';
import StarSystem, { PlanetRings } from './StarSystem';
import Section from '../playermanual/Section';

const FringeWorlds = () => <>
    <h2>Fringe worlds</h2>
    <p>These systems are colonized by humans and are completely self sufficient, but they are also highly isolated and most people who live there have live harsh lives</p>
    <Section title='Ashra'><Ashra /> </Section>
    <Section title='Tonati'><Tonati /> </Section>
</>;

const Tonati = () => <StarSystem
    name='Star System Tonati'
    description='One of many fringe worlds, Tonati considerably advanced with two habitable planets'
    roguePlanetoids={[]}
    stars={[{
        name: 'Tonati',
        description: 'Intense radiation makes the innermost part of the system mostly inaccessible. With a staggering luminosity of 15 times that of the Sun also means that the zone of habitabilty is much larger and farther out.',
        classification: 'A',
        mass: 2.7,
        age: 4.1,
        axialTilt: 0,
        dayPeriod: 3600 * 24,
        imageURL: 'texture_star_tonati.png',
        bodyType: 'star',
        planetoids: [{
            name: 'Chantico',
            description: 'Chantico rotates extremely quickly, a day lasting only 160 minutes. This planet is a smoldering radioactive hellscape under the Tonati sun, rivers of magma flow across the surface that is never able to cool down',
            mass: 0.09,
            age: 3.8,
            classification: 'rocky metallic',
            satelites: [],
            atmosphere: "none",
            atmosphericPressure: 0,
            hydrosphere: "none",
            surfaceGravity: 0.5,
            temperatureRange: [1000, 1200, 1300],
            orbitDistance: { distance: 0.2, unit: 'AU' },
            feature: 'extreme radiation',
            imageURL: 'texture_planet_molten.jpg',
            axialTilt: 6,
            dayPeriod: 3600 * 24 * 10,
            bodyType: 'planetoid',
        },
        {
            name: 'Teylaloc',
            description: 'Large rocky planet with a powerful magnetic field to protect it from the intense solar radiation. Constant thunderstorms and rains of molten lead and graphite makes this planets surface inaccessible.',
            mass: 1.8,
            age: 3.9,
            classification: 'rocky',
            satelites: [],
            atmosphere: "thick carbon dioxide",
            atmosphericPressure: 1700,
            hydrosphere: "none",
            surfaceGravity: 1.5,
            temperatureRange: [320, 340, 360],
            orbitDistance: { distance: 0.7, unit: 'AU' },
            feature: 'constant planetwide thunderstorms',
            imageURL: 'texture_planet_pinkteal.jpg',
            axialTilt: 9,
            dayPeriod: 3600 * 11,
            bodyType: 'planetoid',
        },
        {
            name: 'Atlahua',
            description: 'Small rocky planet with a thin atmosphere of carbondioxide and radiogenic neon (formed by the radiation hitting the magnesium rich surface). Additionally two rings orbit this planet, the inner ring is mostly made of iron and the outer made of silicates. Indicating that they were formed from a failed planet.',
            mass: 0.7,
            age: 3.8,
            classification: 'rocky',
            satelites: [
                new PlanetRings({ distance: 600, unit: 'km' }, [-90, 180, 250], 3.6, 0.01)
            ],
            atmosphere: "80% carbon dioxide, 19% neon, 1% argon",
            atmosphericPressure: 20,
            hydrosphere: "none",
            surfaceGravity: 1.5,
            temperatureRange: [190, 250, 370],
            orbitDistance: { distance: 1.5, unit: 'AU' },
            imageURL: 'texture_planet_rocky.jpg',
            axialTilt: 1,
            dayPeriod: 3600 * 18,
            bodyType: 'planetoid',
        },
        {
            name: 'Ehecatl',
            description: 'Orange moss like flora covers the surface of this world, though the planet has no oceans or large bodies of surface water underground streams can be found. The atmosphere is composed of nitrogen and enough oxygen to breathe, however trace amounts of sulfides in the lower atmosphere makes long term exposure risky.  A small number of settlements exist on this planet, most of them depend on resources from space.',
            mass: 0.5,
            age: 3.7,
            classification: 'rocky',
            satelites: [],
            atmosphere: "60% nitrogen 38% oxygen, 1% argon, 1% ozone, trace sulfides",
            atmosphericPressure: 90,
            hydrosphere: "salt water",
            surfaceGravity: 0.65,
            temperatureRange: [20, 0, 70],
            orbitDistance: { distance: 3.5, unit: 'AU' },
            feature: 'settlements',
            imageURL: 'texture_planet_orangegreen.jpg',
            axialTilt: -21,
            dayPeriod: 3600 * 27,
            bodyType: 'planetoid',
        },
        {
            name: 'Meztil',
            description: 'WIP',
            mass: 0.9,
            age: 3.7,
            classification: 'rocky',
            satelites: [],
            atmosphere: "70% nitrogen 29% oxygen, 1% argon",
            atmosphericPressure: 81,
            hydrosphere: "salt water",
            surfaceGravity: 0.9,
            temperatureRange: [-30, 0, 40],
            orbitDistance: { distance: 4.2, unit: 'AU' },
            feature: 'settlements',
            imageURL: 'texture_planet_lush.jpg',
            axialTilt: 17,
            dayPeriod: 3600 * 28,
            bodyType: 'planetoid',
        },
        {
            name: 'Toci',
            description: 'WIP',
            mass: 65,
            age: 3.9,
            classification: 'gas giant',
            atmosphericPressure: 125320,
            satelites: [],
            atmosphere: "hydrogen helium",
            hydrosphere: "liquid hydrogen",
            surfaceGravity: 4,
            temperatureRange: [-130, 0, 80],
            orbitDistance: { distance: 30, unit: 'AU' },
            imageURL: 'texture_planet_lime.jpg',
            axialTilt: 65,
            dayPeriod: 3600 * 4,
            bodyType: 'planetoid',
        },
        {
            name: 'Xolotl',
            description: 'WIP',
            mass: 1.2,
            age: 6.1,
            classification: 'rocky',
            satelites: [],
            atmosphere: "hydrogen",
            atmosphericPressure: 4,
            hydrosphere: "liquid methane",
            surfaceGravity: 4,
            temperatureRange: [-190, -180, -170],
            orbitDistance: { distance: 79, unit: 'AU' },
            imageURL: 'texture_planet_cold.jpg',
            axialTilt: -90,
            dayPeriod: 3600 * 240,
            bodyType: 'planetoid',
        }
        ]

    }]}
/>

const Ashra = () => <StarSystem
    name='Star System Ashra'
    description='One of many fringe worlds, settled because of the easy access to the water'
    stars={[{
        name: 'Ashra',
        description: 'Ashra is a yellow white main sequence star',
        mass: 0.9,
        age: 4,
        classification: 'K',
        axialTilt: -90,
        dayPeriod: 3600 * 2,
        imageURL: 'texture_star_ashra.png',
        bodyType: 'star',
        planetoids: [{
            name: 'Feshra',
            description: "Innermost planet of Ashra, small planet composed mostly of magnetic iron., it's believed that a stellar event has stripped this planet of its outer mantel leaving only the iron core. The extremely strong magnetic field protects the surface from radiation and allows a dense atmosphere of argon and carbondioxide to persist.",
            mass: 0.1,
            age: 3.6,
            satelites: [],
            classification: "ironball world",
            atmosphere: "90% carbondioxide, 10% argon",
            atmosphericPressure: 173,
            hydrosphere: "none",
            surfaceGravity: 0.5,
            temperatureRange: [400, 450, 500],
            orbitDistance: { distance: 0.1, unit: 'AU' },
            imageURL: 'texture_planet_feshra.png',
            axialTilt: -9,
            dayPeriod: 3600 * 600,
            bodyType: 'planetoid',

        },
        {
            name: 'Noshra',
            description: 'Large brownish green planet',
            mass: 2.9,
            age: 3.6,
            satelites: [
                new PlanetRings({ distance: 600, unit: 'km' }, [90, 180, 190], 3.6, 0.01),
            ],
            classification: 'rocky',
            atmosphere: 'carbondioxide, clouds of sulfides',
            atmosphericPressure: 1862,
            hydrosphere: 'none',
            surfaceGravity: 2.1,
            temperatureRange: [90, 120, 180],
            orbitDistance: { distance: 0.4, unit: 'AU' },

            imageURL: 'texture_planet_noshra.png',
            axialTilt: 1,
            dayPeriod: 3600 * 18,
            bodyType: 'planetoid',
        },
        {
            name: 'Neke',
            description: 'A water world rich in oceanic life, a small number of islands have all been settled by humans, as well as many seasteads that catch sea fauna. '
                + 'Massive space elevators were constructed to facilitate the extraction of water from the planet into space. Neke is also the homeworld of Nekovians, a flying amphibian bipedal race of spaient hunters.',
            mass: 0.7,
            age: 3.6,
            satelites: [],
            classification: 'rocky',
            atmosphere: 'nitrogen 71% oxygen 29%',
            atmosphericPressure: 95,
            hydrosphere: 'salt water',
            surfaceGravity: 0.9,
            temperatureRange: [-20, 10, 60],
            orbitDistance: { distance: 0.8, unit: 'AU' },
            feature: '142 thousand inhabitants',
            imageURL: 'texture_planet_neke.png',
            axialTilt: 15,
            dayPeriod: 3600 * 20,
            bodyType: 'planetoid',
        },
        {
            name: 'Consini belt',
            description: 'The Consini belt is an asteroid belt between Neke and the Sylvis Edis pair.',
            mass: 0.3,
            age: 4,
            satelites: [],
            classification: 'asteroid belt',
            atmosphere: '',
            atmosphericPressure: 0,
            hydrosphere: '',
            surfaceGravity: 0,
            temperatureRange: [-180, -120, 79],
            orbitDistance: { distance: 1.9, unit: 'AU' },
            axialTilt: 0,
            dayPeriod: 3600 * 24,
            bodyType: 'belt',
        },
        {
            name: 'Sylvis',
            description: 'Sylvis & Edis are binary gas giants orbiting',
            mass: 81,
            age: 3.6,
            bodyType: 'planetoid',
            satelites: [{
                name: 'Edis',
                description: 'Edis is believed to be a captured failed star or rogue planet',
                mass: 60,
                age: 9.1,
                classification: 'gas giant',
                atmosphere: 'hydrogen, helium',
                atmosphericPressure: 53224,
                hydrosphere: 'liquid hydrogen',
                surfaceGravity: 3.6,
                temperatureRange: [-120, 0, 10],
                orbitDistance: { distance: 684400, unit: 'km' },
                satelites: [],
                imageURL: 'texture_planet_edis.png',
                axialTilt: 0,
                dayPeriod: 3600 * 8,
                bodyType: 'planetoid',
            }],
            classification: 'gas giant',
            atmosphere: 'hydrogen, helium',
            atmosphericPressure: 83110,
            hydrosphere: 'liquid hydrogen',
            surfaceGravity: 4,
            temperatureRange: [-90, 0, 20],
            orbitDistance: { distance: 4, unit: 'AU' },
            feature: 'asteroid belt orbiting gas giant binary',
            imageURL: 'texture_planet_sylvis.png',
            axialTilt: 0,
            dayPeriod: 3600 * 11,
        },
        {
            name: 'Nane',
            description: 'Frozen ice giant',
            age: 3.8,
            classification: 'ice giant',
            atmosphericPressure: 8000,
            atmosphere: 'hydrogen, helium',
            mass: 19,
            surfaceGravity: 4,
            hydrosphere: 'liquid methane',
            temperatureRange: [-190, -160, -140],
            orbitDistance: { distance: 9, unit: 'AU' },
            satelites: [],
            imageURL: 'texture_planet_nane.png',
            axialTilt: -45,
            dayPeriod: 3600 * 48,
            bodyType: 'planetoid',
        },
        {
            name: 'Sarma',
            description: 'A huge ice giant',
            age: 3.8,
            classification: 'ice giant',
            atmosphericPressure: 12000,
            atmosphere: 'hydrogen, helium',
            mass: 29,
            surfaceGravity: 6,
            hydrosphere: 'liquid methane, liquid nitrogen',
            temperatureRange: [-210, -180, -90],
            orbitDistance: { distance: 20, unit: 'AU' },
            satelites: [],
            imageURL: 'texture_planet_sarma.png',
            axialTilt: -30,
            dayPeriod: 3600 * 36,
            bodyType: 'planetoid',
        },
        {
            name: 'Marzanna',
            description: 'Deep space ice giant',
            age: 3.8,
            classification: 'ice giant',
            atmosphericPressure: 7000,
            atmosphere: 'hydrogen, helium',
            mass: 16,
            surfaceGravity: 4,
            hydrosphere: 'liquid methane, liquid nitrogen',
            temperatureRange: [-220, -190, -130],
            orbitDistance: { distance: 51, unit: 'AU' },
            satelites: [],
            imageURL: 'texture_planet_marzanna.png',
            axialTilt: 0,
            dayPeriod: 3600 * 90,
            bodyType: 'planetoid',
        }
        ]
    }]}
    roguePlanetoids={[]}
/>


export default FringeWorlds;